name: Update README with Medium Blog Posts

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch Medium RSS Feed
      run: curl -s "https://medium.com/feed/@linukaarambawela" -o medium_feed.xml

    - name: Extract Blog Posts
      id: extract_posts
      run: |
        apt-get update && apt-get install -y xmlstarlet
        xmlstarlet sel -t -m '//item[position()<=5]' -v 'concat("<li><a href=\"", link, "\">", title, "</a></li>")' -n medium_feed.xml > blog_posts.html

    - name: Update README
      run: |
        sed -i '/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/{//!d}' README.md
        sed -i '/<!-- BLOG-POST-LIST:START -->/r blog_posts.html' README.md

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update README with latest Medium posts
        branch: main
